  enableInlineShortcodes = false
  [exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [funcs]
    getenv = ['^HUGO_']

  [http]
    methods = ['(?i)GET|POST']
    urls = ['.*']